name: vedientu
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.63.0
  provider: ^6.1.2
  http: ^1.3.0
  dio: ^5.4.2+1
  go_router: ^14.8.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  flutter_animate: ^4.5.0
  mobile_scanner: ^6.0.7
  camera: ^0.10.5+2
  camera_windows: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image_1.jpg
    - assets/images/image_2.jpg
    - assets/images/image_3.jpg
    - assets/images/image_4.jpg
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
