name: vedientu
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # Quản lý trạng thái
  provider: ^6.1.2
  http: 1.3.0
  # Gọi API
  dio: ^5.4.2+1

  # Điều hướng nâng cao
  go_router: ^14.8.1

  # Lưu trữ dữ liệu cục bộ
  shared_preferences: ^2.2.3

  # Hiển thị ảnh
  cached_network_image: ^3.3.1

  # Hỗ trợ SVG
  flutter_svg: ^2.0.10+1

  # Xử lý ngày giờ
  intl: ^0.20.2

  # Hiệu ứng động
  flutter_animate: ^4.5.0
  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
